In [51]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn import metrics
from sklearn.model_selection import train_test_split

### 실습 과제 1. 데이터 불러온 후 NaN 값이 있다면 해당 행 제거하고, train_data : test_data = 7:3 split
#### 종속변수는 PKT_Y, 나머지 변수들이 독립변수

In [40]:
df = pd.read_csv('./data/contest.csv')
df.head()

,No.,LOT_ID,WF_ID,X_AXIS,Y_AXIS,GRADE_CD,G_A,G_B,G_C,G_D,...,Weight_Bound_L,Weight_Bound_M,Weight_Bound_N,Weight_Bound_O,Weight_Bound_P,Weight_Bound_Q,Weight_Bound_R,Weight_Bound_S,Weight_Bound_T,PKT_Y
0,48159,ABC1236,13,59,32,SQ,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0
1,60178,ABC1258,2,45,14,SQ,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0
2,60860,ABC1258,15,50,14,SQ,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.452381,81.583333,0.0,1.0
3,25012,ABC1236,1,45,13,SQ,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0
4,86262,ABC1236,3,51,13,SQ,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0

In [50]:
print(f"df.shape: {df.shape}")
print()

df.info()

df.shape: (1970, 87)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1970 entries, 0 to 2498
Data columns (total 87 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   No.             1970 non-null   int64
 1   LOT_ID          1970 non-null   object
 2   WF_ID           1970 non-null   int64
 3   X_AXIS          1970 non-null   int64
 4   Y_AXIS          1970 non-null   int64
 5   GRADE_CD        1970 non-null   object
 6   G_A             1970 non-null   int64
 7   G_B             1970 non-null   int64
 8   G_C             1970 non-null   int64
 9   G_D             1970 non-null   int64
 10  G_E             1970 non-null   int64
 11  G_F             1970 non-null   int64
 12  G_G             1970 non-null   int64
 13  G_H             1970 non-null   float64
 14  G_I             1970 non-null   int64
 15  G_J             1970 non-null   int64
 16  G_K             1970 non-null   int64
 17  G_L             1970 non-null   int64
 18  G_M             1970 non-null   int64
 19  G_N             1970 non-null   int64
 20  G_O             1970 non-null   int64
 21  G_P             1970 non-null   int64
 22  G_Q             1970 non-null   int64
 23  G_R             1970 non-null   int64
 24  G_S             1970 non-null   int64
 25  G_T             1970 non-null   int64
 26  Neighbor_A      1970 non-null   int64
 27  Neighbor_B      1970 non-null   int64
 28  Neighbor_C      1970 non-null   int64
 29  Neighbor_D      1970 non-null   int64
 30  Neighbor_E      1970 non-null   int64
 31  Neighbor_F      1970 non-null   int64
 32  Neighbor_G      1970 non-null   int64
 33  Neighbor_H      1970 non-null   float64
 34  Neighbor_I      1970 non-null   int64
 35  Neighbor_J      1970 non-null   int64
 36  Neighbor_K      1970 non-null   int64
 37  Neighbor_L      1970 non-null   int64
 38  Neighbor_M      1970 non-null   int64
 39  Neighbor_N      1970 non-null   int64
 40  Neighbor_O      1970 non-null   int64
 41  Neighbor_P      1970 non-null   int64
 42  Neighbor_Q      1970 non-null   int64
 43  Neighbor_R      1970 non-null   int64
 44  Neighbor_S      1970 non-null   int64
 45  Neighbor_T      1970 non-null   int64
 46  Weight_Base_A   1970 non-null   float64
 47  Weight_Base_B   1970 non-null   float64
 48  Weight_Base_C   1970 non-null   float64
 49  Weight_Base_D   1970 non-null   float64
 50  Weight_Base_E   1970 non-null   float64
 51  Weight_Base_F   1970 non-null   float64
 52  Weight_Base_G   1970 non-null   float64
 53  Weight_Base_H   1970 non-null   float64
 54  Weight_Base_I   1970 non-null   float64
 55  Weight_Base_J   1970 non-null   float64
 56  Weight_Base_K   1970 non-null   float64
 57  Weight_Base_L   1970 non-null   float64
 58  Weight_Base_M   1970 non-null   float64
 59  Weight_Base_N   1970 non-null   float64
 60  Weight_Base_O   1970 non-null   float64
 61  Weight_Base_P   1970 non-null   float64
 62  Weight_Base_Q   1970 non-null   float64
 63  Weight_Base_R   1970 non-null   float64
 64  Weight_Base_S   1970 non-null   float64
 65  Weight_Base_T   1970 non-null   float64
 66  Weight_Bound_A  1970 non-null   float64
 67  Weight_Bound_B  1970 non-null   float64
 68  Weight_Bound_C  1970 non-null   float64
 69  Weight_Bound_D  1970 non-null   float64
 70  Weight_Bound_E  1970 non-null   float64
 71  Weight_Bound_F  1970 non-null   float64
 72  Weight_Bound_G  1970 non-null   float64
 73  Weight_Bound_H  1970 non-null   float64
 74  Weight_Bound_I  1970 non-null   float64
 75  Weight_Bound_J  1970 non-null   float64
 76  Weight_Bound_K  1970 non-null   float64
 77  Weight_Bound_L  1970 non-null   float64
 78  Weight_Bound_M  1970 non-null   float64
 79  Weight_Bound_N  1970 non-null   float64
 80  Weight_Bound_O  1970 non-null   float64
 81  Weight_Bound_P  1970 non-null   float64
 82  Weight_Bound_Q  1970 non-null   float64
 83  Weight_Bound_R  1970 non-null   float64
 84  Weight_Bound_S  1970 non-null   float64
 85  Weight_Bound_T  1970 non-null   float64
 86  PKT_Y           1970 non-null   float64
dtypes: float64(43), int64(42), object(2)
memory usage: 1.3+ MB

In [42]:
df.describe(include='all')

,No.,LOT_ID,WF_ID,X_AXIS,Y_AXIS,GRADE_CD,G_A,G_B,G_C,G_D,...,Weight_Bound_L,Weight_Bound_M,Weight_Bound_N,Weight_Bound_O,Weight_Bound_P,Weight_Bound_Q,Weight_Bound_R,Weight_Bound_S,Weight_Bound_T,PKT_Y
count,2500.000000,2500,2500.000000,2500.000000,2500.000000,2500,2500.000000,2500.00000,2500.000000,2500.000000,...,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,1970.000000
unique,NaN,3,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,ABC1258,NaN,NaN,NaN,SQ,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1231,NaN,NaN,NaN,1751,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,58457.710800,NaN,12.842000,38.779200,27.032400,NaN,1.639200,1.61560,1.766000,1.844800,...,1.100230,0.884604,0.974666,1.695392,2.443549,2.272934,7.761293,8.533709,1.167709,0.507614
std,35589.053486,NaN,7.460409,14.360339,8.964212,NaN,6.968246,6.90615,7.029183,6.442524,...,10.618900,8.894689,10.097390,18.942232,22.176382,22.150841,38.262314,38.278556,10.442140,0.500069
min,105.000000,NaN,1.000000,11.000000,11.000000,NaN,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,27833.750000,NaN,6.000000,27.000000,20.000000,NaN,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,57130.000000,NaN,13.000000,38.000000,27.000000,NaN,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,85205.750000,NaN,19.000000,51.000000,34.000000,NaN,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,128225.000000,NaN,25.000000,68.000000,44.000000,NaN,84.000000,84.00000,84.000000,60.000000,...,244.642857,239.819444,247.500000,683.416667,618.750000,617.291667,600.000000,611.619048,341.714286,1.000000

In [46]:
num_null = df.isnull().sum()
num_null[num_null != 0]

PKT_Y    530
dtype: int64

In [47]:
df = df.dropna(subset=['PKT_Y'], how='any')

In [49]:
df.shape

(1970, 87)

In [62]:
X = df[df.columns[6:-1]]
Y = df['PKT_Y']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state=10)

print(f"train dataset size: {x_train.shape}")
print(f"test dataset size: {x_test.shape}")

train dataset size: (1379, 80)
test dataset size: (591, 80)

### 실습 과제 2. 선형 커널, 3차항 커널, RBF 커널, 시그모이드 커널로 각각 SVM 모델 구현 후 accuracy, F1 score, confusion matrix, precision, recall (C=1, gamma = 0.1)

In [66]:
svm_linear = svm.SVC(kernel='poly', degree=1, C=1, gamma=0.1)
svm_poly = svm.SVC(kernel='poly', degree=3, C=1, gamma=0.1)
svm_rbf = svm.SVC(kernel='rbf', C=1, gamma=0.1)
svm_sig = svm.SVC(kernel='sigmoid', C=1, gamma=0.1)

svm_model_names = ['linear', 'poly', 'rbf', 'sig']
svm_models = [svm_linear, svm_poly, svm_rbf, svm_sig]

for name, model in zip(svm_model_names, svm_models):
    print(f"model name is svm_{name}")
    print('-'*50)
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print(f"accuracy: {metrics.accuracy_score(y_test, y_pred)}")
    print(f"f1_score: {metrics.f1_score(y_test, y_pred)}")
    print(f"precision_score: {metrics.precision_score(y_test, y_pred)}")
    print(f"recall_score: {metrics.recall_score(y_test, y_pred)}")
    print(f"confusion_mtrx: \n{metrics.confusion_matrix(y_test, y_pred)}")
    print()

model name is svm_linear
--------------------------------------------------
accuracy: 0.5803722504230119
f1_score: 0.4979757085020242
precision_score: 0.6507936507936508
recall_score: 0.40327868852459015
confusion_mtrx:
[[220  66]
 [182 123]]

model name is svm_poly
--------------------------------------------------
accuracy: 0.5820642978003384
f1_score: 0.5240847784200385
precision_score: 0.6355140186915887
recall_score: 0.4459016393442623
confusion_mtrx:
[[208  78]
 [169 136]]

model name is svm_rbf
--------------------------------------------------
accuracy: 0.5769881556683587
f1_score: 0.6458923512747875
precision_score: 0.5685785536159601
recall_score: 0.7475409836065574
confusion_mtrx:
[[113 173]
 [ 77 228]]

model name is svm_sig
--------------------------------------------------
accuracy: 0.36717428087986465
f1_score: 0.3848684210526316
precision_score: 0.38613861386138615
recall_score: 0.3836065573770492
confusion_mtrx:
[[100 186]
 [188 117]]

### 실습 과제 3. 하이퍼 파라미터 C 값(0.01, 0.1, 1, 10)에 따른 RBF 커널을 SVM 모델의 accuracy와 F1 score 변화 관찰

In [71]:
C_list = [0.01, 0.1, 1, 10]

for c_value in C_list:
    svm_rbf = svm.SVC(kernel='rbf', C=c_value, gamma=0.1)
    svm_rbf.fit(x_train, y_train)
    y_pred = svm_rbf.predict(x_test)
    
    print(f"c value: {c_value}")
    print(f"accuracy: {metrics.accuracy_score(y_test, y_pred)}")
    print(f"f1_score: {metrics.f1_score(y_test, y_pred)}")
    print('-'*30)

c value: 0.01
accuracy: 0.5160744500846024
f1_score: 0.6808035714285715
------------------------------
c value: 0.1
accuracy: 0.5465313028764806
f1_score: 0.6555269922879178
------------------------------
c value: 1
accuracy: 0.5769881556683587
f1_score: 0.6458923512747875
------------------------------
c value: 10
accuracy: 0.5702199661590525
f1_score: 0.6520547945205479
------------------------------

### 실습 과제 4. 하이퍼 파라미터 gamma 값(0.005,0.01,0.1, 1)에 따른 RBF 커널을 SVM 모델의 accuracy와 F1 score 변화 관찰

In [72]:
gamma_list = [0.005, 0.01, 0.1, 1]

for gamma_value in gamma_list:
    svm_rbf = svm.SVC(kernel='rbf', C=1, gamma=gamma_value)
    svm_rbf.fit(x_train, y_train)
    y_pred = svm_rbf.predict(x_test)
    
    print(f"gamma value: {gamma_value}")
    print(f"accuracy: {metrics.accuracy_score(y_test, y_pred)}")
    print(f"f1_score: {metrics.f1_score(y_test, y_pred)}")
    print('-'*30)

gamma value: 0.005
accuracy: 0.6040609137055838
f1_score: 0.5894736842105263
------------------------------
gamma value: 0.01
accuracy: 0.6006768189509306
f1_score: 0.6143790849673203
------------------------------
gamma value: 0.1
accuracy: 0.5769881556683587
f1_score: 0.6458923512747875
------------------------------
gamma value: 1
accuracy: 0.544839255499154
f1_score: 0.6699386503067485
------------------------------

### 실습 과제 5. 하이퍼 파라미터 degree(1,2,3,4,5)에 따른 다항식 커널 SVM 모델 accuracy와 F1 score 변화 관찰

In [73]:
degree_list = [1,2,3,4,5]

for value in degree_list:
    svm_poly = svm.SVC(kernel='poly', degree=value, C=1, gamma=0.1)
    svm_poly.fit(x_train, y_train)
    y_pred = svm_poly.predict(x_test)
    
    print(f"degree: {value}")
    print(f"accuracy: {metrics.accuracy_score(y_test, y_pred)}")
    print(f"f1_score: {metrics.f1_score(y_test, y_pred)}")
    print('-'*30)

degree: 1
accuracy: 0.5803722504230119
f1_score: 0.4979757085020242
------------------------------
degree: 2
accuracy: 0.5668358714043993
f1_score: 0.5133079847908745
------------------------------
degree: 3
accuracy: 0.5820642978003384
f1_score: 0.5240847784200385
------------------------------
degree: 4
accuracy: 0.5820642978003384
f1_score: 0.5330812854442345
------------------------------
degree: 5
accuracy: 0.583756345177665
f1_score: 0.5477941176470589
------------------------------